version: '3.8'

services:
  # WordPress service
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - /home/abderrafie/data/wordpress:/var/www/html
    networks:
      - network
    ports:
      - "9000:9000"

  # MariaDB service
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - /home/abderrafie/data/mariadb:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - /home/abderrafie/data/wordpress:/var/www/html
    restart: always
    networks:
      - network

volumes:
  wordpress_data:
  mariadb_data:

networks:
  network:
    driver: bridge