version: '3.8'

services:
  # # WordPress service
  # wordpress:
  #   build:
  #     context: ./requirements/wordpress
  #   container_name: wordpress
  #   environment:
  #     WORDPRESS_DB_HOST: mariadb:3306
  #     WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
  #     WORDPRESS_DB_USER: ${MYSQL_USER}
  #     WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - frontend

  # MariaDB service
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  # NGINX service
  # nginx:
  #   build:
  #     context: ./requirements/nginx
  #   container_name: nginx
  #   environment:
  #     DOMAIN_NAME: ${DOMAIN_NAME}
  #   volumes:
  #     - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  #     - ./requirements/nginx/ssl:/etc/nginx/ssl
  #     - wordpress_data:/var/www/html
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   depends_on:
  #     - wordpress
  #   networks:
  #     - frontend

volumes:
  wordpress_data:
  mariadb_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
